window.XDIGMA_CONTENT = {
  en: {
    htmlLang: "en",
    title: "Xdigma — We Help Your Brand Get Found and Trusted Online",
    description: "Digital marketing for UMKM and growing brands. We handle the strategy, websites, SEO, and content so you don't have to figure it all out alone.",
    skip: "Skip to content",
    loader: "Loading ecosystem",
    backTop: "Top",
    menu: "Menu",
    close: "Close",
    nav: ["Studio", "Work", "Services", "Contact"],
    navCta: "Let's Talk",
    whatsappMessage: "Hi Xdigma, I want to grow my brand online.",
    whatsappLabel: "WhatsApp 0813 1770 613",
    heroKicker: ["Digital marketing studio", "Jakarta / Remote"],
    eyebrow: "Your business is running. Let's make sure people can find it.",
    rotator: ["Get found online", "Look the part", "Grow steadily"],
    heroTitle: "We help brands show up in the right place, at the right time.",
    latestProject: "Latest project",
    latestProjectFallback: "Selected work",
    heroSide: "From branding to SEO — we figure out what your brand needs and get it done. You'll always know the price before we start.",
    marquee: ["Brand Identity", "Website Design", "SEO & Content", "Social Media", "Brand Identity", "Website Design", "SEO & Content", "Social Media"],
    scroll: "Scroll",
    aboutLabel: "About",
    introLead: "We're a small digital marketing studio that works closely with founders and growing businesses.",
    introBody: "No big agency overhead. No confusing packages. Just the work your brand actually needs.",
    recentWork: "Recent work",
    seeAll: "See all projects",
    recentWorkLoading: "Loading projects",
    recentWorkError: "Projects could not be loaded",
    recentWorkRetry: "Try again",
    attitude: "How we think",
    rules: [
      ["No. 1", "Do the useful thing first.", "A good-looking brand that doesn't convert is just expensive decoration."],
      ["No. 2", "Don't overcomplicate it.", "Most brands don't need more — they need the right things done well."],
      ["No. 3", "Launching is just the start.", "We stick around to see what's working and what needs adjusting."],
      ["No. 4", "Be honest about what we don't know.", "We'd rather say 'let's figure it out' than pretend we have all the answers."],
      ["No. 5", "Leave things better than we found them.", "Clean work, documented handoffs — so you're never stuck without us."]
    ],
    partnershipTitle: "Industries we work with",
    partnershipBody: "Focused experience across education, food and beverage, and local businesses building a stronger digital presence.",
    industries: ["Education", "Food & Beverage", "Local Business"],
    servicesTitle: "What we do",
    servicesBody: "Pick what you need. We'll tell you honestly if something else makes more sense for your situation.",
    services: ["Brand Identity Design", "Website Design & Front-End Dev", "SEO & Content Systems", "Social Media Branding"],
    serviceDescriptions: [
      "A clear visual system that makes your brand recognizable, consistent, and ready to grow.",
      "Strategy, UX, visual design, and production-ready front-end in one focused build.",
      "Search-ready structure and content systems that help people find you and understand your offer.",
      "A consistent social identity and content system that keeps every post recognizably yours."
    ],
    serviceIncludesLabel: "Includes",
    serviceCta: "Ask about this",
    serviceClose: "Close",
    serviceAriaClose: "Close service detail",
    serviceDetails: [
      ["Brand Identity Design", "A flexible identity system that makes your brand easier to recognize and apply consistently.", ["Brand positioning", "Logo and brand marks", "Color and typography system", "Visual direction", "Brand guidelines and assets"]],
      ["Website Design & Front-End Dev", "Strategy, interface design, and a fast responsive build handled as one connected process.", ["Discovery and information architecture", "Wireframes and user flows", "Responsive UI design", "HTML/CSS/JavaScript development", "Performance and accessibility pass"]],
      ["SEO & Content Systems", "Search-ready pages and repeatable content structures that make your offer easier to find and understand.", ["Search intent mapping", "Content architecture", "Landing-page systems", "Metadata and internal linking", "Editorial templates"]],
      ["Social Media Branding", "A recognizable social presence with visual rules and templates your team can keep using.", ["Profile and art direction", "Social visual system", "Reusable content templates", "Content pillars", "Handoff-ready asset library"]]
    ],
    selectedCapability: "Selected capability",
    processTitle: "How a project usually goes",
    processBody: "Simple, and we walk you through every part.",
    process: [
      ["We get to know your business", "What you sell, who you're trying to reach, and what's not working yet."],
      ["We plan before we build", "No jumping straight into design — we agree on direction first so nothing gets wasted."],
      ["We build, launch, and follow up", "After launch, we check in to see what the numbers are saying."]
    ],
    metricsTitle: "What we focus on in every project.",
    metricLabels: [
      "Make the offer easier to understand",
      "Keep the brand recognizable everywhere",
      "Help the right people find you",
      "Leave a system your team can continue"
    ],
    metricTicker: ["Brand clarity", "Visual consistency", "Search visibility", "Responsive experience", "Reusable systems", "Clean handoff"],
    awardsTitle: "Trained and certified.",
    awards: ["Certified", "Certified", "Certified"],
    faqTitle: "Frequently asked questions",
    faqItems: [
      ["Can we start without a finished brief?", "Yes. Tell us about your business, what's not working, and what you want to improve. We'll help shape the direction."],
      ["Can we choose just one service?", "Yes. The scope follows what the project needs. You do not have to take a full package."],
      ["How long does a project usually take?", "Most projects take 2 to 8 weeks, depending on scope, feedback, and content readiness."],
      ["How much does a project cost?", "We quote after the scope is clear, so you know what is included before committing."],
      ["Who owns the files and access after handoff?", "You do. Final assets, source files, and project access are handed over when the project is complete."],
      ["Can we work remotely?", "Yes. Planning, reviews, and handoff can all happen online."]
    ],
    availabilityKicker: "Availability",
    availabilityTitle: "Every project is priced around what you actually need.",
    availabilityLink: ["Tell us your situation first"," we'll give you an honest number before you commit to anything."],
    contactKicker: "Not sure where to start? That's fine — most people aren't.",
    contactTitle: "Tell us what's going on with your brand. We'll take it from there.",
    contactForm: {
      title: "Send us a brief",
      subtitle: "Or just describe what's on your mind.",
      fields: ["Name", "Email", "Project type", "Timeline", "Budget range", "What's going on?"],
      placeholders: ["Your name", "you@brand.com", "No need to have it figured out — just tell us the situation."],
      emptyOptions: ["Choose one", "Choose one", "Choose a range"],
      types: ["Brand Identity Design", "Website Design & Front-End Dev", "SEO & Content Systems", "Social Media Branding"],
      timelines: ["2-4 weeks", "1-2 months", "Quarter launch", "Still figuring it out"],
      budgets: ["Under IDR 750 thousand", "IDR 750 thousand - 5 million", "IDR 5 - 10 million", "Above IDR 10 million", "Not decided yet"],
      whatsapp: {
        greeting: "Hi Xdigma,",
        intro: "I want to start a project. Here is my brief:",
        labels: ["Name", "Email", "Project type", "Timeline", "Budget range", "Project context"]
      },
      submit: "Send it over",
      success: "WhatsApp draft opened. Send it and we'll reply there."
    },
    footerKicker: "Xdigma Creative Studio",
    footerTitle: "We're easy to reach.",
    footerHeadings: ["Studio", "Services", "Social"],
    footerStudio: ["About", "Work", "Services", "Contact"],
    footerServices: ["Brand identity design", "Website design & front-end dev", "SEO & content systems", "Social media branding"],
    newsletter: "Newsletter",
    newsletterPlaceholder: "Email address",
    newsletterJoin: "Join",
    newsletterSuccess: "Email draft opened. Send it and you're on the list.",
    footerBottom: ["©2026 Xdigma Creative Studio", "Jakarta / Remote"],
    caseSelected: "What came out of it",
    caseLabels: ["The situation", "What we did"],
    caseMetaLabels: ["Timeline", "Role", "Stack"],
    caseDeliverables: "Deliverables",
    caseCta: "Talk to us about something similar",
    caseClose: "Close",
    caseAriaClose: "Close case study"
  },
  id: {
    htmlLang: "id",
    title: "Xdigma — Bantu Brand Lo Lebih Gampang Ditemuin dan Dipercaya",
    description: "Digital marketing buat UMKM dan bisnis yang lagi berkembang. Kami urus strategi, website, SEO, dan konten — biar lo gak perlu figuring out semuanya sendiri.",
    skip: "Langsung ke konten",
    loader: "Lagi nyiapin semuanya",
    backTop: "Atas",
    menu: "Menu",
    close: "Tutup",
    nav: ["Studio", "Portofolio", "Layanan", "Kontak"],
    navCta: "Ngobrol Dulu",
    whatsappMessage: "Halo Xdigma, gua mau ngembangin brand gua secara online.",
    whatsappLabel: "WhatsApp 0813 1770 613",
    heroKicker: ["Studio digital marketing", "Jakarta / Remote"],
    eyebrow: "Bisnis lo udah jalan. Sekarang pastiin orang bisa nemuin lo.",
    rotator: ["Gampang ditemuin", "Keliatan profesional", "Tumbuh pelan tapi pasti"],
    heroTitle: "Kami bantu brand lo muncul di tempat yang tepat, di waktu yang tepat.",
    latestProject: "Project terbaru",
    latestProjectFallback: "Karya pilihan",
    heroSide: "Dari branding sampai SEO — kami cari tau apa yang brand lo butuhkan dan langsung kerjain. Harga selalu dikasih tau sebelum mulai.",
    marquee: ["Identitas Brand", "Desain Website", "SEO & Konten", "Media Sosial", "Identitas Brand", "Desain Website", "SEO & Konten", "Media Sosial"],    scroll: "Scroll",
    aboutLabel: "Tentang",
    introLead: "Kami studio digital marketing kecil yang kerja dekat sama founder dan bisnis yang lagi tumbuh.",
    introBody: "Gak ada overhead agency besar. Gak ada paket yang bikin bingung. Cuma kerjaan yang emang dibutuhkan brand lo.",
    recentWork: "Karya terbaru",
    seeAll: "Lihat semua project",
    recentWorkLoading: "Lagi memuat project",
    recentWorkError: "Project belum bisa dimuat",
    recentWorkRetry: "Coba lagi",
    attitude: "Cara kami mikir",
    rules: [
      ["No. 1", "Kerjain yang berguna dulu.", "Brand yang keliatan bagus tapi gak convert itu cuma dekorasi mahal."],
      ["No. 2", "Jangan bikin ribet.", "Kebanyakan brand gak butuh lebih banyak — mereka butuh hal yang tepat dikerjain dengan bener."],
      ["No. 3", "Launch itu baru awal.", "Kami tetap pantau setelah launch buat liat apa yang jalan dan apa yang perlu disesuain."],
      ["No. 4", "Jujur kalau belum tau.", "Kami lebih milih bilang 'ayo cari tau bareng' daripada pura-pura punya semua jawabannya."],
      ["No. 5", "Tinggalin sesuatu yang lebih baik.", "Kerjaan yang rapi dan handoff yang terdokumentasi — biar lo gak stuck kalau butuh kami lagi."]
    ],
    partnershipTitle: "Industri yang kami bantu",
    partnershipBody: "Pengalaman langsung bersama bisnis pendidikan, kuliner, dan usaha lokal yang lagi memperkuat kehadiran digital.",
    industries: ["Pendidikan", "Kuliner & F&B", "Bisnis Lokal"],
    servicesTitle: "Yang kami kerjain",
    servicesBody: "Pilih yang lo butuh. Kami bakal jujur kalau ada yang lebih masuk akal buat situasi lo.",
    services: ["Desain Identitas Brand", "Desain Website & Front-End Dev", "SEO & Sistem Konten", "Branding Media Sosial"],
    serviceDescriptions: [
      "Sistem visual yang bikin brand lo gampang dikenali, konsisten, dan siap berkembang.",
      "Strategi, UX, desain visual, dan front-end siap produksi dalam satu proses yang fokus.",
      "Struktur dan sistem konten yang bantu orang nemuin serta memahami apa yang lo tawarkan.",
      "Identitas sosial dan sistem konten konsisten yang bikin setiap post tetap terasa punya brand lo."
    ],
    serviceIncludesLabel: "Yang termasuk",
    serviceCta: "Tanya soal ini",
    serviceClose: "Tutup",
    serviceAriaClose: "Tutup detail layanan",
    serviceDetails: [
      ["Desain Identitas Brand", "Sistem identitas fleksibel yang bikin brand lo lebih gampang dikenali dan dipakai secara konsisten.", ["Positioning brand", "Logo dan brand mark", "Sistem warna dan tipografi", "Arah visual", "Panduan brand dan aset"]],
      ["Desain Website & Front-End Dev", "Strategi, desain interface, dan build responsif yang cepat dikerjain sebagai satu proses terhubung.", ["Discovery dan information architecture", "Wireframe dan user flow", "Desain UI responsif", "Development HTML/CSS/JavaScript", "Audit performa dan aksesibilitas"]],
      ["SEO & Sistem Konten", "Halaman siap pencarian dan struktur konten berulang yang bikin penawaran lo lebih mudah ditemukan dan dipahami.", ["Pemetaan search intent", "Arsitektur konten", "Sistem landing page", "Metadata dan internal linking", "Template editorial"]],
      ["Branding Media Sosial", "Kehadiran sosial yang gampang dikenali dengan aturan visual dan template yang bisa terus dipakai tim lo.", ["Arah profil dan visual", "Sistem visual sosial media", "Template konten reusable", "Pilar konten", "Library aset siap handoff"]]
    ],
    selectedCapability: "Kapabilitas pilihan",
    processTitle: "Biasanya project jalan kayak gini",
    processBody: "Simpel, dan kami temani di setiap bagiannya.",
    process: [
      ["Kami kenalan sama bisnis lo", "Apa yang lo jual, siapa yang lo coba jangkau, dan apa yang belum jalan."],
      ["Kami plan sebelum build", "Gak langsung loncat ke desain — kami sepakatin arahnya dulu biar gak ada yang kebuang."],
      ["Kami build, launch, dan follow up", "Setelah launch, kami cek balik buat liat apa yang dikasih tau angkanya."]
    ],
    metricsTitle: "Yang kami fokuskan di setiap project.",
    metricLabels: [
      "Bikin penawaran lebih mudah dipahami",
      "Jaga brand tetap mudah dikenali di mana pun",
      "Bantu orang yang tepat menemukan brand lo",
      "Tinggalkan sistem yang bisa tim lo lanjutkan"
    ],
    metricTicker: ["Kejelasan brand", "Konsistensi visual", "Mudah ditemukan", "Pengalaman responsif", "Sistem reusable", "Handoff rapi"],
    awardsTitle: "Terlatih dan tersertifikasi.",
    awards: ["Certified", "Certified", "Certified"],
    faqTitle: "Pertanyaan yang sering ditanyain",
    faqItems: [
      ["Bisa mulai kalau belum punya brief?", "Bisa. Ceritain bisnis lo, apa yang belum jalan, dan apa yang mau diperbaiki. Kami bantu rapihin arahnya."],
      ["Bisa ambil satu layanan saja?", "Bisa. Scope mengikuti kebutuhan project, jadi lo gak harus mengambil paket lengkap."],
      ["Berapa lama satu project berjalan?", "Umumnya 2 sampai 8 minggu, tergantung scope, kecepatan feedback, dan kesiapan konten."],
      ["Berapa biaya project-nya?", "Harga kami susun setelah scope jelas, jadi lo tahu apa saja yang termasuk sebelum mulai."],
      ["Setelah project selesai, file dan akses jadi milik siapa?", "Milik lo. Aset final, source file, dan akses project diserahkan saat project selesai."],
      ["Bisa kerja remote?", "Bisa. Planning, review, dan handoff bisa dilakukan online."]
    ],
    availabilityKicker: "Ketersediaan",
    availabilityTitle: "Setiap project kami hargain sesuai kebutuhannya.",
    availabilityLink: ["Ceritain situasi lo dulu"," kami kasih gambaran harga yang jujur sebelum lo commit apapun."],
    contactKicker: "Belum tau harus mulai dari mana? Gak apa-apa — kebanyakan orang juga gitu.",
    contactTitle: "Ceritain situasi brand lo. Kami yang lanjutin dari sana.",
    contactForm: {
      title: "Kirim brief",
      subtitle: "Atau ceritain aja apa yang ada di pikiran lo.",
      fields: ["Nama", "Email", "Tipe project", "Timeline", "Range budget", "Situasinya gimana?"],
      placeholders: ["Nama lo", "lo@brand.com", "Gak harus udah kepikiran semuanya — ceritain aja situasinya."],
      emptyOptions: ["Pilih satu", "Pilih satu", "Pilih range"],
      types: ["Desain Identitas Brand", "Desain Website & Front-End Dev", "SEO & Sistem Konten", "Branding Media Sosial"],
      timelines: ["2-4 minggu", "1-2 bulan", "Launch kuartal ini", "Masih dirapihin"],
      budgets: ["Di bawah Rp750 ribu", "Rp750 ribu - Rp5 juta", "Rp5 - Rp10 juta", "Di atas Rp10 juta", "Belum ditentukan"],
      whatsapp: {
        greeting: "Halo Xdigma,",
        intro: "Gua mau mulai project. Ini brief singkatnya:",
        labels: ["Nama", "Email", "Tipe project", "Timeline", "Range budget", "Situasi project"]
      },
      submit: "Kirim",
      success: "Draft WhatsApp kebuka. Kirim, nanti kami balas di sana."
    },
    footerKicker: "Xdigma Creative Studio",
    footerTitle: "Gampang dihubungi.",
    footerHeadings: ["Studio", "Layanan", "Sosial"],
    footerStudio: ["Tentang", "Karya", "Layanan", "Kontak"],
    footerServices: ["Desain identitas brand", "Desain website & front-end dev", "SEO & sistem konten", "Branding media sosial"],
    newsletter: "Newsletter",
    newsletterPlaceholder: "Alamat email",
    newsletterJoin: "Gabung",
    newsletterSuccess: "Draft email kebuka. Kirim, nanti lo masuk list.",
    footerBottom: ["©2026 Xdigma Creative Studio", "Jakarta / Remote"],
    caseSelected: "Yang keluar dari project ini",
    caseLabels: ["Situasinya", "Yang kami lakuin"],
    caseMetaLabels: ["Timeline", "Peran", "Stack"],
    caseDeliverables: "Deliverables",
    caseCta: "Ngobrol soal sesuatu yang mirip",
    caseClose: "Tutup",
    caseAriaClose: "Tutup studi kasus"
  }
};
